### PR TITLE
Import urlencode in python 2/3 compatible way

### LINKED ISSUE #26: Python 3: CRITICAL Alphabot failed. Reason: API call "rtm.start" to Slack failed: module 'urllib' has no attribute 'urlencode'
Method changed in Python 3. See https://stackoverflow.com/a/28906913

https://github.com/Nextdoor/alphabot/blob/30914b67c78219d67e5ec460cd80ad103b94f3ed/alphabot/bot.py#L505
https://github.com/Nextdoor/alphabot/blob/30914b67c78219d67e5ec460cd80ad103b94f3ed/alphabot/bot.py#L650

### PR DESCRIPTION
**Pull request by mikhail**
Closes #26 

cc: @macropin

### CODE REVIEW

**Comment by mikhail** [comment]
@mcropin thanks for pointing this out. I'm not good at keeping up to date with python 2/3 compatible

**Comment by mikhail** [comment]
@macropin thanks for pointing this out

**Comment by mrterry** [comment]
Is there any reason to support python 2?  Why not just drop python 2 support and move on with life?

**Comment by mikhail** [comment]
True... I'll start the work to move in a separate PR

**Pull request merged**
